### ISSUE TITLE
Mark's final read through

### ISSUE THREAD

**Issue by canismarko** [m3wolf/perspective-paper#8]

**Comment by canismarko** [comment]
Closed by 9108e09bb655147513861d0774c651e5e9835370

**Comment by brianmay19** [comment]
Sections have been rearranged. I ended up removing one of the references regarding phase contrast imaging in the section on spectromicroscopy. Seems like building the pdf was OK, but can you double check to make sure it's good to go?

**Comment by canismarko** [comment]
Paper has been published
